version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_service
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password

  anomaly_detection:
    build: ./anomaly-detection
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URI=mongodb://mongo_user:mongo_password@mongo_service:27017/vessel_data
    depends_on:
      - mongo

  vessel_ingestion:
    build: ./vessel-ingestion
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URI=mongodb://mongo_user:mongo_password@mongo_service:27017/vessel_data
    depends_on:
      - mongo

  vessel_cargo_association:
    build: ./vessel-cargo-association
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URI=mongodb://mongo_user:mongo_password@mongo_service:27017/vessel_data
    depends_on:
      - mongo