apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection-service
spec:
  type: ClusterIP
  selector:
    app: anomaly-detection
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002

