apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detection-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anomaly-detection
  template:
    metadata:
      labels:
        app: anomaly-detection
    spec:
      containers:
      - name: anomaly-detection
        image: astaomars/anomaly-detection:latest
        ports:
        - containerPort: 5002
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"  