apiVersion: apps/v1
kind: Deployment
metadata:
  name: vessel-ingestion-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vessel-ingestion
  template:
    metadata:
      labels:
        app: vessel-ingestion
    spec:
      containers:
      - name: vessel-ingestion
        image: astaomars/vessel-ingestion:latest
        ports:
        - containerPort: 5001
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"  