apiVersion: v1
kind: Service
metadata:
  name: vessel-cargo-association-service
spec:
  type: ClusterIP
  selector:
    app: vessel-cargo-association
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003

