# Base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the files to the container
COPY . /app

# Install dependencies
RUN pip install -r requirements.txt

# Expose port
EXPOSE 5003

# Command to run the app
CMD ["python", "app.py"]
